# Generated by Django 5.2 on 2025-05-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('app_autenticacion', '__first__'),
        ('app_categorias', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaProductosAgropecuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('url_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.distrito')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_categorias.producto')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincia')),
                ('tipoproducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_categorias.tipoproducto')),
                ('usuariosistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_autenticacion.usuariosistema')),
            ],
            options={
                'db_table': 'demandaproductosagropecuarios',
            },
        ),
    ]
