# Generated by Django 5.2 on 2025-07-14 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('app_autenticacion', '0001_initial'),
        ('app_categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDemandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
            ],
            options={
                'db_table': 'tiposdemandas',
            },
        ),
        migrations.CreateModel(
            name='Demandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('localidadcaserio', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia_ubicacion', models.TextField(blank=True, null=True)),
                ('contacto', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_categorias.producto')),
                ('tipoproducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_categorias.tipoproducto')),
                ('usuariosistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_autenticacion.usuariosistema')),
                ('tiposdemandas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_demandas.tiposdemandas')),
            ],
            options={
                'db_table': 'demandas',
            },
        ),
    ]
