# Generated by Django 5.2 on 2025-07-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('app_demandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.distrito'),
        ),
    ]
