# Generated by Django 5.2 on 2025-05-30 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('app_autenticacion', '0001_initial'),
        ('app_categorias', '0001_initial'),
        ('app_demandas', '0002_tiposdemandas_demandas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='localidadcaserio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.localidadcaserio'),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_categorias.producto'),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='tipoproducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_categorias.tipoproducto'),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='tiposdemandas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_demandas.tiposdemandas'),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='usuariosistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_autenticacion.usuariosistema'),
        ),
    ]
