# Generated by Django 5.2 on 2025-05-30 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_conversionunidadmedida_estado_and_more'),
        ('app_demandas', '0003_alter_demandas_email_alter_demandas_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposdemandas',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
    ]
