# Generated by Django 5.2 on 2025-04-18 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('app_categorias', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioCiudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_enero', models.FloatField(blank=True, null=True)),
                ('valor_febrero', models.FloatField(blank=True, null=True)),
                ('valor_marzo', models.FloatField(blank=True, null=True)),
                ('valor_abril', models.FloatField(blank=True, null=True)),
                ('valor_mayo', models.FloatField(blank=True, null=True)),
                ('valor_junio', models.FloatField(blank=True, null=True)),
                ('valor_julio', models.FloatField(blank=True, null=True)),
                ('valor_agosto', models.FloatField(blank=True, null=True)),
                ('valor_septiembre', models.FloatField(blank=True, null=True)),
                ('valor_octubre', models.FloatField(blank=True, null=True)),
                ('valor_noviembre', models.FloatField(blank=True, null=True)),
                ('valor_diciembre', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('conversionunidadmedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.conversionunidadmedida')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.producto')),
            ],
            options={
                'db_table': 'preciociudades',
            },
        ),
        migrations.CreateModel(
            name='PreciosMercadoMayoristaMinorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_equivalente_kilogramo_litro', models.FloatField(blank=True, null=True)),
                ('precio_minimo', models.FloatField(blank=True, null=True)),
                ('precio_promedio', models.FloatField(blank=True, null=True)),
                ('precio_maximo', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.producto')),
                ('unidadmedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidadmedida')),
            ],
            options={
                'db_table': 'preciosmercadomayoristaminorista',
            },
        ),
    ]
