# Generated by Django 5.2 on 2025-05-30 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_conversionunidadmedida_estado_and_more'),
        ('app_categorias', '0002_alter_producto_estado_alter_producto_tipoproducto_and_more'),
        ('app_registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciociudades',
            name='conversionunidadmedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.conversionunidadmedida'),
        ),
        migrations.AlterField(
            model_name='preciociudades',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
        migrations.AlterField(
            model_name='preciociudades',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_categorias.producto'),
        ),
        migrations.AlterField(
            model_name='preciosmercadomayoristaminorista',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
        migrations.AlterField(
            model_name='preciosmercadomayoristaminorista',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_categorias.producto'),
        ),
        migrations.AlterField(
            model_name='preciosmercadomayoristaminorista',
            name='unidadmedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.unidadmedida'),
        ),
    ]
