# Generated by Django 5.2 on 2025-04-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciociudades',
            name='valor_anual',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
