# Generated by Django 5.2 on 2025-05-30 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionunidadmedida',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.pais'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.provincia'),
        ),
        migrations.AlterField(
            model_name='localidadcaserio',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.distrito'),
        ),
        migrations.AlterField(
            model_name='localidadcaserio',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
        migrations.AlterField(
            model_name='mercado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.departamento'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
    ]
