# Generated by Django 5.2 on 2025-06-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado')),
            ],
            options={
                'db_table': 'tipodocumento',
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecompleto', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('numerodedocumento', models.CharField(blank=True, max_length=11, null=True)),
                ('numero_celular', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('terminos_condiciones', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.distrito')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.provincia')),
                ('tipodedocumento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_autenticacion.tipodocumento')),
            ],
            options={
                'db_table': 'usuariosistema',
            },
        ),
    ]
