# Generated by Django 5.2 on 2025-05-30 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_conversionunidadmedida_estado_and_more'),
        ('app_autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosistema',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
    ]
