# Generated by Django 5.2 on 2025-05-13 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('app_categorias', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('asunto', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precioalquiler', models.FloatField(blank=True, null=True)),
                ('termino', models.TextField(blank=True, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.producto')),
                ('submaquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.subproducto')),
                ('tipomaquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.tipoproducto')),
            ],
            options={
                'db_table': 'anunciomaquinaria',
            },
        ),
        migrations.CreateModel(
            name='AnuncioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('salario', models.FloatField(blank=True, null=True)),
                ('periodoingreso', models.DateTimeField(blank=True, null=True)),
                ('periodofinal', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
            ],
            options={
                'db_table': 'anunciotrabajo',
            },
        ),
        migrations.CreateModel(
            name='TipoAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
            ],
            options={
                'db_table': 'tipoanuncio',
            },
        ),
        migrations.CreateModel(
            name='AnuncioCompraVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('asunto', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('termino', models.TextField(blank=True, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.producto')),
                ('subproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.subproducto')),
                ('tipoproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.tipoproducto')),
                ('unidadmedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidadmedida')),
                ('tipoanuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_anuncios.tipoanuncio')),
            ],
            options={
                'db_table': 'anunciocompraventa',
            },
        ),
    ]
