# Generated by Django 5.2 on 2025-05-30 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_conversionunidadmedida_estado_and_more'),
        ('app_anuncios', '0001_initial'),
        ('app_categorias', '0002_alter_producto_estado_alter_producto_tipoproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunciocompraventa',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
        migrations.AlterField(
            model_name='anunciocompraventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_categorias.producto'),
        ),
        migrations.AlterField(
            model_name='anunciocompraventa',
            name='subproducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_categorias.subproducto'),
        ),
        migrations.AlterField(
            model_name='anunciocompraventa',
            name='tipoanuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_anuncios.tipoanuncio'),
        ),
        migrations.AlterField(
            model_name='anunciocompraventa',
            name='tipoproducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_categorias.tipoproducto'),
        ),
        migrations.AlterField(
            model_name='anunciocompraventa',
            name='unidadmedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.unidadmedida'),
        ),
        migrations.AlterField(
            model_name='anunciomaquinaria',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
        migrations.AlterField(
            model_name='anunciomaquinaria',
            name='maquinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_categorias.producto'),
        ),
        migrations.AlterField(
            model_name='anunciomaquinaria',
            name='submaquinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_categorias.subproducto'),
        ),
        migrations.AlterField(
            model_name='anunciomaquinaria',
            name='tipomaquinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_categorias.tipoproducto'),
        ),
        migrations.AlterField(
            model_name='anunciotrabajo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
        migrations.AlterField(
            model_name='tipoanuncio',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
    ]
