# Generated by Django 5.2 on 2025-04-24 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('app_categorias', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertasCerealesLegumbres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/ofertas_cerealeslegumbres/')),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.TextField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('web', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.distrito')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.producto')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincia')),
            ],
            options={
                'db_table': 'ofertascerealeslegumbres',
            },
        ),
        migrations.CreateModel(
            name='OfertasFrutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/ofectas_frutas/')),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.TextField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('web', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.distrito')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.producto')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincia')),
            ],
            options={
                'db_table': 'ofectasfrutas',
            },
        ),
        migrations.CreateModel(
            name='OfertasInsumoTecnologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/ofertas_insumotecnologico/')),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.TextField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('web', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.distrito')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.producto')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincia')),
            ],
            options={
                'db_table': 'ofertasinsumotecnologico',
            },
        ),
        migrations.CreateModel(
            name='OfertasPastosForrajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/ofertas_pastosforrajes/')),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.TextField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('web', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.distrito')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.producto')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincia')),
            ],
            options={
                'db_table': 'ofertaspastosforrajes',
            },
        ),
        migrations.CreateModel(
            name='OfertasProductosLacteos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/ofertas_productoslacteos/')),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.TextField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('web', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.distrito')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.producto')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincia')),
            ],
            options={
                'db_table': 'ofertasproductoslacteos',
            },
        ),
        migrations.CreateModel(
            name='OfertasServicioAgrario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/ofertas_servicioagrario/')),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.TextField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('web', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.distrito')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.producto')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincia')),
            ],
            options={
                'db_table': 'ofertasservicioagrario',
            },
        ),
        migrations.CreateModel(
            name='OfertasTuberculosRaices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/ofertas_tuberculosraices/')),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.TextField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('web', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.distrito')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.producto')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincia')),
            ],
            options={
                'db_table': 'ofertastuberculosraices',
            },
        ),
    ]
