# Generated by Django 5.2 on 2025-05-30 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_conversionunidadmedida_estado_and_more'),
        ('app_autenticacion', '0002_alter_usuariosistema_estado'),
        ('app_categorias', '0002_alter_producto_estado_alter_producto_tipoproducto_and_more'),
        ('app_ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.distrito'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_categorias.producto'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.provincia'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='tipoproducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_categorias.tipoproducto'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='usuariosistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_autenticacion.usuariosistema'),
        ),
        migrations.AlterField(
            model_name='tiposofertas',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estado'),
        ),
    ]
