# Generated by Django 5.2 on 2025-06-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='web',
            field=models.TextField(blank=True, null=True),
        ),
    ]
